// <auto-generated />
namespace UniversitymanagementUsingEntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StudentV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202008170038135_StudentV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
